{% set name = "scikits.odes" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/scikits.odes/scikits_odes-{{ version }}.tar.gz
    sha256: 7255ca51d7acd32c844244e535276a7119111a9edeea9ea36c60ee51d738a0d9
  - url: https://pypi.org/packages/source/s/scikits-odes-core/scikits_odes_core-{{ version }}.tar.gz
    sha256: 9225c10e5e8f417fef7e9411895036c9ec580e73d262653f97f54fdee30e8fb7
    folder: scikits-odes-core
  - url: https://pypi.org/packages/source/s/scikits-odes-daepack/scikits_odes_daepack-{{ version }}.tar.gz
    sha256: 26ff10369819e4e115253238542acfe4440a03a41792a7a2d741d57d4eb92569
    folder: sckits-odes-daepack
  - url: https://pypi.org/packages/source/s/scikits-odes-sundials/scikits_odes_sundials-{{ version }}.tar.gz
    sha256: 277d0400812f63a11624565d82f9ecc7497263ebfb9f049e5ca8ab2d025c5621
    folder: sckites-odes-sundials

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-dependencies --no-build-isolation scikits-odes-core/ -vv
    - {{ PYTHON }} -m pip install --no-dependencies --no-build-isolation scikits-odes-sundials/ -vv
    - {{ PYTHON }} -m pip install --no-dependencies --no-build-isolation scikits-odes-daepack/ -vv
    - {{ PYTHON }} -m pip install --no-dependencies --no-build-isolation . -vv

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - meson-python
    - numpy                                  # [build_platform != target_platform]
    - pkgconfig
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
  host:
    - cython <3
    - libblas
    - numpy
    - pip
    - python
    - setuptools <=64.0.0
    - sundials >=6.0.0,<7
  run:
    - numpy
    - python
    - scipy
    - sundials >=6.0.0,<7

test:
  imports:
    - scikits.odes
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/bmcage/odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A python module for ordinary differential equation anddifferential algebraic equation solvers
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the Sundials solvers cvode, cvodes, ida and idas. It this way
    it provides extra modern ode and dae solvers you can use, extending the
    capabilities offered in scipy.integrade.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - moorepants
