{% set name = "scikits.odes" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/scikits.odes/scikits_odes-{{ version }}.tar.gz
    sha256: 78c22d07ac1fee7dfa1734641a338801a97078827cade831b3ca2b191264f340
  - url: https://pypi.org/packages/source/s/scikits-odes-core/scikits_odes_core-{{ version }}.tar.gz
    sha256: 3d40235eb5b365b8908f8c093dadf1f71f5bb52cfeacbee03403c6882f3e077b
    folder: scikits-odes-core
  - url: https://pypi.org/packages/source/s/scikits-odes-daepack/scikits_odes_daepack-3.0.0.tar.gz
    sha256: 26ff10369819e4e115253238542acfe4440a03a41792a7a2d741d57d4eb92569
    folder: scikits-odes-daepack
  - url: https://pypi.org/packages/source/s/scikits-odes-sundials/scikits_odes_sundials-{{ version }}.tar.gz
    sha256: b32fbfb8628d3e7d3d4aec3df9adc394d2323aef125b366caeeaca29c89ed64f
    folder: scikits-odes-sundials
build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install -vv --no-dependencies --no-build-isolation scikits-odes-core/
    - {{ PYTHON }} -m pip install -vv --no-dependencies --no-build-isolation scikits-odes-sundials/
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig                                    # [build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-dependencies --no-build-isolation scikits-odes-daepack/ -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-dependencies --no-build-isolation scikits-odes-daepack/  # [not unix]
    - {{ PYTHON }} -m pip install --no-dependencies --no-build-isolation . -vv

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - libblas
    - meson-python
    - more-itertools  # dependency of setuptools
    - numpy
    - pip
    - pkgconfig
    - python
    - setuptools
    - sundials >=7
  run:
    - numpy
    - python
    - scipy
    - sundials >=7

test:
  imports:
    - scikits.odes
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/bmcage/odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A python module for ordinary differential equation anddifferential algebraic equation solvers
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the Sundials solvers cvode, cvodes, ida and idas. It this way
    it provides extra modern ode and dae solvers you can use, extending the
    capabilities offered in scipy.integrade.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - moorepants
