{% set name = "scikits.odes" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a71e19e1485893754ae8c050668232fcc694f17b83602e75fbebf7bf9f975e1e

build:
  number: 1
  # NOTE : There is a pyproject.yml file that seems to force wheels to be built
  # so remove it.
  script:
    - /bin/rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('fortran') }}
  host:
    - cython <3.0
    - libblas
    - numpy
    - pip
    - python
    - setuptools <=64.0.0
    - sundials >=6.0.0,<7
  run:
    - python
    - scipy
    - sundials >=6.0.0,<7
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - scikits.odes
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/bmcage/odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A python module for ordinary differential equation anddifferential algebraic equation solvers
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the Sundials solvers cvode, cvodes, ida and idas. It this way
    it provides extra modern ode and dae solvers you can use, extending the
    capabilities offered in scipy.integrade.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - moorepants
