{% set name = "scikits.odes" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a71e19e1485893754ae8c050668232fcc694f17b83602e75fbebf7bf9f975e1e

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-dependencies . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - scikits-odes-core
    - scikits-odes-daepack
    - scikits-odes-sundials
    - scipy

test:
  imports:
    - scikits.odes
  files:
    - integrate.py
  commands:
    - python integrate.py

outputs:
  - name: scikits-odes-core
    version: {{ version }}
    source:
      url: https://pypi.org/packages/source/s/scikits-odes-core/scikits-odes-core-{{ version }}.tar.gz
      sha256: 9225c10e5e8f417fef7e9411895036c9ec580e73d262653f97f54fdee30e8fb7
    requirements:
      host:
        - pip
        - python
        - setuptools
      run:
        - python
  - name: scikits-odes-daepack
    version: {{ version }}
    source:
      url: https://pypi.org/packages/source/s/scikits-odes-daepack/scikits-odes-daepack-{{ version }}.tar.gz
      sha256: 26ff10369819e4e115253238542acfe4440a03a41792a7a2d741d57d4eb92569
    requirements:
      build:
        - meson-python
        - numpy
      host:
        - pip
        - python
        - setuptools
      run:
        - python
        - scikits-odes-core =={{ version }}
  - name: scikits-odes-sundials
    version: {{ version }}
    source:
      url: https://pypi.org/packages/source/s/scikits-odes-sundials/scikits-odes-sundials-{{ version }}.tar.gz
      sha256: 277d0400812f63a11624565d82f9ecc7497263ebfb9f049e5ca8ab2d025c5621
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython <3                              # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pkgconfig
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('fortran') }}
      host:
        - cython <3
        - libblas
        - numpy
        - pip
        - python
        - setuptools <=64.0.0
        - sundials >=6.0.0,<7
      run:
        - numpy
        - python
        - scikits-odes-core =={{ version }}
        - sundials >=6.0.0,<7

about:
  home: https://github.com/bmcage/odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A python module for ordinary differential equation anddifferential algebraic equation solvers
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the Sundials solvers cvode, cvodes, ida and idas. It this way
    it provides extra modern ode and dae solvers you can use, extending the
    capabilities offered in scipy.integrade.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - moorepants
